setup:
  path: models/bee-world/
  gym_name: BeeWorld
  algorithm: TD3
  alias: round3
  continue_training: True
  old_alias: round2

train: 
  timesteps: 2000
  iter_max: 10
  policy_kwargs: { net_arch: [100 ,100], activation_fn: ReLU }
  learning_rate: 0.001

test:
  prediction_step: 1000

