setup:
  path: models/bee-world-1ml/
  alias: round1

  continue_training: False
  old_alias: round1
env:
  algorithm: TD3
  gym_name: BeeWorld
  render_mode: rgb_array
  walls: [
        # [[5.0, 0.0], [5.0, 5.0]],
        # [[2.5, 10.0], [2.5, 6.0]],
    ]
  goal_size: 2.0
  video: True
  agent_location_range: [[0.0, 2.0], [0.0, 10.0]]
  goal_location_range: [[5.0, 10.0], [0.0, 10.0]]

train: 
  timesteps: 1_000_000
  max_episode_steps: 3000
  policy_kwargs: { net_arch: [300, 200], activation_fn: ReLU }
  learning_rate: 0.001
  max_no_improvement_evals: 200
  eval_freq: 1000


test:
  prediction_steps: 1000


