setup:
  path: models/bee-world-250k/
  alias: round1

  continue_training: False
  old_alias: round1
env:
  algorithm: TD3
  gym_name: BeeWorld
  render_mode: rgb_array
  walls: [
        [[5.0, 0.0], [5.0, 5.0]],
        [[2.5, 10.0], [2.5, 6.0]],
    ]
  goal_size: 0.5
  video: True

train: 
  timesteps: 250_000
  max_episode_steps: 5000
  policy_kwargs: { net_arch: [200, 100], activation_fn: ReLU }
  learning_rate: 0.001
  max_no_improvement_evals: 100
  eval_freq: 1000


test:
  prediction_steps: 1000


